[stdin]:1
const fs=require('fs');const s=fs.readFileSync('repo-work/index.html','utf8');const js=[...s.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).filter(x=>x.trim()).join('\n');new Function(js);for(const m of ['PAGE_SIZE=10','OVERRIDE_API','method:isEdit?','data-source=','showSeq?`<span class="seq">'])if(!s.includes(m))throw Error('missing '+m);if(s.includes('class="mark'))throw Error('icon remains');console.log('VALID');
                                                                                                                                                                                                                                                                                                                                                ^

Error: missing method:isEdit?
    at [stdin]:1:343
    at runScriptInThisContext (node:internal/vm:219:10)
    at node:internal/process/execution:451:12
    at [stdin]-wrapper:6:24
    at runScriptInContext (node:internal/process/execution:449:60)
    at evalFunction (node:internal/process/execution:283:30)
    at evalTypeScript (node:internal/process/execution:295:3)
    at node:internal/main/eval_stdin:51:5
    at Socket.<anonymous> (node:internal/process/execution:205:5)
    at Socket.emit (node:events:520:35)

Node.js v24.14.0
create table if not exists public.manual_entries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 30),
  amount integer not null check (amount between 1 and 10000000),
  type text not null check (type in ('계좌', '현금')),
  detail text not null default '' check (char_length(detail) <= 80),
  created_at timestamptz not null default now()
);

alter table public.manual_entries enable row level security;

grant select, insert, update on table public.manual_entries to anon, authenticated;
grant usage, select on sequence public.manual_entries_id_seq to anon, authenticated;

drop policy if exists "manual_entries_read" on public.manual_entries;
create policy "manual_entries_read"
on public.manual_entries for select
to anon, authenticated
using (true);

drop policy if exists "manual_entries_insert" on public.manual_entries;
create policy "manual_entries_insert"
on public.manual_entries for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 30
  and amount between 1 and 10000000
  and type in ('계좌', '현금')
  and char_length(detail) <= 80
);

create table if not exists public.entry_overrides (
  base_order integer primary key check (base_order between 1 and 10000),
  name text not null check (char_length(name) between 1 and 30),
  amount integer not null check (amount between 1 and 10000000),
  type text not null check (type in ('계좌', '현금')),
  detail text not null default '' check (char_length(detail) <= 80),
  updated_at timestamptz not null default now()
);

alter table public.entry_overrides enable row level security;
grant select, insert, update on table public.entry_overrides to anon, authenticated;

drop policy if exists "entry_overrides_read" on public.entry_overrides;
create policy "entry_overrides_read"
on public.entry_overrides for select
to anon, authenticated
using (true);

drop policy if exists "entry_overrides_insert" on public.entry_overrides;
create policy "entry_overrides_insert"
on public.entry_overrides for insert
to anon, authenticated
with check (
  base_order between 1 and 10000
  and char_length(name) between 1 and 30
  and amount between 1 and 10000000
  and type in ('계좌', '현금')
  and char_length(detail) <= 80
);

drop policy if exists "entry_overrides_update" on public.entry_overrides;
create policy "entry_overrides_update"
on public.entry_overrides for update
to anon, authenticated
using (true)
with check (
  base_order between 1 and 10000
  and char_length(name) between 1 and 30
  and amount between 1 and 10000000
  and type in ('계좌', '현금')
  and char_length(detail) <= 80
);

drop policy if exists "manual_entries_update" on public.manual_entries;
create policy "manual_entries_update"
on public.manual_entries for update
to anon, authenticated
using (true)
with check (
  char_length(name) between 1 and 30
  and amount between 1 and 10000000
  and type in ('계좌', '현금')
  and char_length(detail) <= 80
);
